<?php
//controller
"{Controller}"=>array(
        "name"=>"{Controller}",
        "actions"=>array(
            "edit{Table}"=>array(
                "Type"=>"simple"//"AJAX"
                ,'Role'=>"edit"
                ,"view"=>array(
                  "view"=>true
                  ,"layout"=>false
                  ,"pages"=>array(
                        "edit"=>"edit{Table}"
                        ,"lister"=>"lister{Table}"
                        //,"id"=>"id{Table}"
                      )
                )
                ,"activity"=>"edit"
                ,"form"=>"form{Table}"
                ,"model"=>array(
                    "table"=>"{Table}"
                )
            ),

            "lister{Table}"=>array(
                "Type"=>"simple"//"AJAX"
                ,'Role'=>"lister"
                ,"view"=>array(
                              "view"=>true
                              ,"layout"=>false
                              ,"pages"=>array(
                                    "edit"=>"edit{Table}"
                                    ,"lister"=>"lister{Table}"
                                    ,"consulter"=>"consulter{Table}"
                                    ,"id"=>"id{Table}"
                                  )
              )
                ,"activity"=>"lister{Table}"
                ,"form"=>false
                ,"model"=>array(
                        "table"=>"{Table}"
                    )

            ),
            "consulter{Table}"=>array(
                "Type"=>"simple"//"AJAX"
                ,'Role'=>"consulter"
                ,"view"=>array(
                              "view"=>true
                              ,"layout"=>false
                              ,"pages"=>array(
                                    "edit"=>"edit{Table}"
                                    ,"lister"=>"lister{Table}"
                                    ,"id"=>"id{Table}"
                                  )
              )
                ,"activity"=>"consulter{Table}"
                ,"form"=>false
                ,"model"=>array(
                        "table"=>"{Table}"
                    )

            ),
            "gestion{Table}"=>array(
                "Type"=>"simple"//"AJAX"
                ,'Role'=>"gestion"
                ,"view"=>array(
                        "view"=>true
                        ,"layout"=>"layout"
                        ,"pages"=>array(
                          "edit"=>"edit{Table}"
                          ,"lister"=>"lister{Table}"
                        )
                    )
                ,"activity"=>"gestion"
                ,"form"=>false
                ,"model"=>array(
                    "table"=>"{Table}"
                )

            ),
            "delete{Table}"=>array(
                "Type"=>"AJAX"//"AJAX"
                ,'Role'=>"delete"
                ,"view"=>array("view"=>false,"layout"=>false)
                ,"activity"=>"delete"
                ,"form"=>false
                ,"model"=>array(
                    "table"=>"{Table}"
                )
            ),
            "save{Table}"=>array(
                "Type"=>"AJAX"//"AJAX"
                ,'Role'=>"save"
                ,"view"=>array("view"=>false,"layout"=>false)
                ,"activity"=>"save"
                ,"form"=>false
                ,"model"=>array(
                    "table"=>"{Table}"
                )
            ),
        ),
    )
