<?php

$_APP_CONF=array(
    "APPNAME"=>"gestcomp"
);
$_Config=array(
    "modules"=>array(
        "admin"=>array(
            "name"=>"admin"
            ,"Controller"=>array(
             "centraleregional"=>array(
                    "name"=>"centraleregional",
                    "actions"=>array(
                        "editcentraleregional"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"edit"
                            ,"view"=>array(
                              "view"=>true
                              ,"layout"=>false
                              ,"pages"=>array(
                                    "edit"=>"editcentraleregional"
                                    ,"lister"=>"listercentraleregional"
                                    //,"id"=>"idcentraleregional"
                                  )


                            )
                            ,"activity"=>"edit"
                            ,"form"=>"formcentraleregional"
                            ,"model"=>array(
                                "table"=>"centraleregional"
                            )
                        ),

                        "listercentraleregional"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"lister"
                            ,"view"=>array(
                                          "view"=>true
                                          ,"layout"=>false
                                          ,"pages"=>array(
                                                "edit"=>"editcentraleregional"
                                                ,"lister"=>"listercentraleregional"
                                                ,"consulter"=>"consultercentraleregional"
                                                ,"id"=>"idcentraleregional"
                                              )
                          )
                            ,"activity"=>"listercentraleregional"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"centraleregional"
                                )

                        ),
                        "consultercentraleregional"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"consulter"
                            ,"view"=>array(
                                          "view"=>true
                                          ,"layout"=>false
                                          ,"pages"=>array(
                                                "edit"=>"editcentraleregional"
                                                ,"lister"=>"listercentraleregional"
                                                ,"id"=>"idcentraleregional"
                                              )
                          )
                            ,"activity"=>"consultercentraleregional"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"centraleregional"
                                )

                        ),
                        "gestioncentraleregional"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"gestion"
                            ,"view"=>array(
                                    "view"=>true
                                    ,"layout"=>"layout"
                                    ,"pages"=>array(
                                      "edit"=>"editcentraleregional"
                                      ,"lister"=>"listercentraleregional"
                                    )
                                )
                            ,"activity"=>"gestion"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"centraleregional"
                            )

                        ),
                        "deletecentraleregional"=>array(
                            "Type"=>"AJAX"//"AJAX"
                            ,'Role'=>"delete"
                            ,"view"=>array("view"=>false,"layout"=>false)
                            ,"activity"=>"delete"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"centraleregional"
                            )
                        ),
                        "savecentraleregional"=>array(
                            "Type"=>"AJAX"//"AJAX"
                            ,'Role'=>"save"
                            ,"view"=>array("view"=>false,"layout"=>false)
                            ,"activity"=>"save"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"centraleregional"
                            )
                        ),
                    ),
                )
            ,"ecole"=>array(
                    "name"=>"ecole",
                    "actions"=>array(
                        "editecole"=>array(
                         "Type"=>"simple"//"AJAX"
                        ,'Role'=>"edit"
                        ,"view"=>array("view"=>true,"layout"=>"layout")
                        ,"activity"=>"editecole"
                        ,"form"=>"formecole"
                        ,"model"=>array(
                                "table"=>"ecole"
                            )
                        ),
                        "listerecole"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"lister"
                            ,"view"=>array("view"=>true,"layout"=>"layout")
                            ,"activity"=>"listerecole"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"ecole"
                                )
                        ),
                        "deleteecole"=>array(
                            "Type"=>"AJAX"//"AJAX"
                        ,'Role'=>"delete"
                        ,"view"=>array("view"=>false,"layout"=>false)
                        ,"activity"=>"deleteecole"
                        ,"form"=>false
                        ,"model"=>array(
                                "table"=>"ecole"
                            )
                        ),
                        "saveecole"=>array(
                            "Type"=>"AJAX"//"AJAX"
                            ,'Role'=>"save"
                            ,"view"=>array("view"=>false,"layout"=>false)
                            ,"activity"=>"save"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"ecole"
                            )
                        ),
                        "gestionecole"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"gestion"
                            ,"view"=>array(
                                    "view"=>true
                                    ,"layout"=>"layout"
                                    ,"pages"=>array(
                                      "edit"=>"editecole"
                                      ,"lister"=>"listerecole"
                                    )
                                )
                            ,"activity"=>"gestion"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"ecole"
                            )

                        ),
                        "editniveaux"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"edit"
                            ,"view"=>array("view"=>true,"layout"=>"layout")
                            ,"activity"=>"editniveaux"
                            ,"form"=>"formniveaux"
                            ,"model"=>array(
                                "table"=>"niveaux"
                            )
                        ),
                        "listerniveaux"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"lister"
                            ,"view"=>array("view"=>true,"layout"=>"layout")
                            ,"activity"=>"listerniveaux"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"niveaux"
                                )
                        ),
                        "deleteniveaux"=>array(
                            "Type"=>"AJAX"//"AJAX"
                        ,'Role'=>"delete"
                        ,"view"=>array("view"=>false,"layout"=>false)
                        ,"activity"=>"deleteniveaux"
                        ,"form"=>false
                        ,"model"=>array(
                                "table"=>"niveaux"
                            )
                        ),
                        "saveniveaux"=>array(
                            "Type"=>"AJAX"//"AJAX"
                        ,'Role'=>"save"
                        ,"view"=>array("view"=>false,"layout"=>false)
                        ,"activity"=>"saveniveaux"
                        ,"form"=>false
                        ,"model"=>array(
                                "table"=>"niveaux"
                            )
                        ),
                        "editsection"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"edit"
                            ,"view"=>array("view"=>true,"layout"=>"layout")
                            ,"activity"=>"editsection"
                            ,"form"=>"formsection"
                            ,"model"=>array(
                                    "table"=>"sections"
                                )
                        ),
                        "listersections"=>array(
                            "Type"=>"simple"//"AJAX"
                            ,'Role'=>"lister"
                            ,"view"=>array("view"=>true,"layout"=>"layout")
                            ,"activity"=>"listersections"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"sections"
                                )
                            ),
                        "deletesection"=>array(
                            "Type"=>"AJAX"//"AJAX"
                            ,'Role'=>"delete"
                            ,"view"=>array("view"=>false,"layout"=>false)
                            ,"activity"=>"deletesection"
                            ,"form"=>false
                            ,"model"=>array(
                                    "table"=>"sections"
                                )
                        ),
                        "savesection"=>array(
                            "Type"=>"AJAX"//"AJAX"
                            ,'Role'=>"save"
                            ,"view"=>array("view"=>false,"layout"=>false)
                            ,"activity"=>"savesection"
                            ,"form"=>false
                            ,"model"=>array(
                                "table"=>"sections"
                            )
                        ),
                    ),
                )

            ),
        )
    ),
    "Menue"=>array(
                 "Referentiel"=>array(
                    "titre"=>"MENU_REFERENTIEL",
                    "url"=>array(
                        "Module"=>"referentiel"
                        ,"Controller"=>"gestionreferentiel"
                        ,"Action"=>"gestionreferentiel"
                        ,"Roles"=>array(
                            "Admin"=>array(//actions
                                "ADD",
                                "DEL",
                                "MODIF",
                                "LISTER",
                                "CONSULT",
                            )
                        )
                    ),
                    "activity"=>array( //interface View
                        "type"=>"complex", //complex : view double (sasie + liste)
                        "Mode"=>"AJAX",
                        "interface"=>array(
                               "edit"=>array(
                                   "url"=>array(
                                       "Module"=>"referentiel"
                                       ,"Controller"=>"gestionreferentiel"
                                       ,"Action"=>"gestionreferentiel"
                                       ,"Type"=>array("ADD","MODIF")
                                       ,"Roles"=>array(
                                               "Admin"=>array(//actions
                                                   "ADD",
                                                   "DEL",
                                                   "MODIF",
                                                   "LISTER",
                                                   "CONSULT",
                                               )
                                           )
                                       ),
                               ),
                               "liste"=>array(
                                   "titre"=>array("LANG"=>"TITRE_GEST_REF","DEFAULT"=>"Gestion de réferentiel"),
                                   "url"=>array(
                                       "Module"=>"referentiel"
                                       ,"Controller"=>"gestionreferentiel"
                                       ,"Action"=>"gestionreferentiel"
                                       ,"Type"=>array("LISTER", "CONSULT","GEST")
                                       ,"Roles"=>array(
                                               "Admin"=>array(//droits
                                                   "ADD",
                                                   "DEL",
                                                   "MODIF",
                                                   "LISTER",
                                                   "CONSULT",
                                                   "GEST",
                                               )
                                           )
                                       ),
                               )

                        )
                    ),
                )
    )
);
