<script>

    $(function(){


        var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { },
            success: function() { },
            complete: function(response)
            {


                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                    $("#messageEditpersonnes_Titre").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\lib\Langue::getString('Success_save_personnes')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");

                       loadPage("listerpersonnes","content_listerpersonnes");

                    $("#personnes")[0].reset();

                }else{

                    $("#messageEditpersonnes_Titre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\lib\Langue::getString('Error_save_personnes')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");


                }
                return true;

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#messageEditpersonnes_Titre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'><?=\lib\Langue::getString('Success_save_personnes')?></h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#personnes").ajaxForm(optmyform);


    });
</script>

<div id="messageEditpersonnes_Titre"></div>
<h1><?=\lib\Langue::getString("Edit_personnes")?></h1>
<?=$this->form?>
