<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_instituteur')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editinstituteur","edit_editinstituteur");
        loadPage("listerinstituteur","content_listerinstituteur");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_instituteur")?></div>
            <div class="box-body" id="edit_editinstituteur">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_instituteur")?></div>
            <div class="box-body" id="content_listerinstituteur">

            </div>
        </div>
    </div>
</div>
