<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_matiere')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editmatiere","edit_editmatiere");
        loadPage("listermatiere","content_listermatiere");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_matiere")?></div>
            <div class="box-body" id="edit_editmatiere">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_matiere")?></div>
            <div class="box-body" id="content_listermatiere">

            </div>
        </div>
    </div>
</div>
