"editcontenucours"=>array(
    "Type"=>"simple"//"AJAX"
    ,'Role'=>"edit"
    ,"view"=>array(
      "view"=>true
      ,"layout"=>false
      ,"pages"=>array(
            "edit"=>"editcontenucours"
            ,"lister"=>"listercontenucours"
            //,"id"=>"idcontenucours"
          )
    )
    ,"activity"=>"edit"
    ,"form"=>"formcontenucours"
    ,"model"=>array(
        "table"=>"contenucours"
    )
),

"listercontenucours"=>array(
    "Type"=>"simple"//"AJAX"
    ,'Role'=>"lister"
    ,"view"=>array(
                  "view"=>true
                  ,"layout"=>false
                  ,"pages"=>array(
                        "edit"=>"editcontenucours"
                        ,"lister"=>"listercontenucours"
                        ,"consulter"=>"consultercontenucours"
                        ,"id"=>"idcontenucours"
                      )
  )
    ,"activity"=>"listercontenucours"
    ,"form"=>false
    ,"model"=>array(
            "table"=>"contenucours"
        )

),
"consultercontenucours"=>array(
    "Type"=>"simple"//"AJAX"
    ,'Role'=>"consulter"
    ,"view"=>array(
                  "view"=>true
                  ,"layout"=>false
                  ,"pages"=>array(
                        "edit"=>"editcontenucours"
                        ,"lister"=>"listercontenucours"
                        ,"id"=>"idcontenucours"
                      )
  )
    ,"activity"=>"consultercontenucours"
    ,"form"=>false
    ,"model"=>array(
            "table"=>"contenucours"
        )

),
"gestioncontenucours"=>array(
    "Type"=>"simple"//"AJAX"
    ,'Role'=>"gestion"
    ,"view"=>array(
            "view"=>true
            ,"layout"=>"layout"
            ,"pages"=>array(
              "edit"=>"editcontenucours"
              ,"lister"=>"listercontenucours"
            )
        )
    ,"activity"=>"gestion"
    ,"form"=>false
    ,"model"=>array(
        "table"=>"contenucours"
    )

),
"deletecontenucours"=>array(
    "Type"=>"AJAX"//"AJAX"
    ,'Role'=>"delete"
    ,"view"=>array("view"=>false,"layout"=>false)
    ,"activity"=>"delete"
    ,"form"=>false
    ,"model"=>array(
        "table"=>"contenucours"
    )
),
"savecontenucours"=>array(
    "Type"=>"AJAX"//"AJAX"
    ,'Role'=>"save"
    ,"view"=>array("view"=>false,"layout"=>false)
    ,"activity"=>"save"
    ,"form"=>false
    ,"model"=>array(
        "table"=>"contenucours"
    )
  ),
  //conpetence savesections
  "editcompetences"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"edit"
      ,"view"=>array(
        "view"=>true
        ,"layout"=>false
        ,"pages"=>array(
              "edit"=>"editcompetences"
              ,"lister"=>"listercompetences"
              //,"id"=>"idcompetences"
            )
      )
      ,"activity"=>"edit"
      ,"form"=>"formcompetences"
      ,"model"=>array(
          "table"=>"competences"
      )
  ),

  "listercompetences"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"lister"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editcompetences"
                          ,"lister"=>"listercompetences"
                          ,"consulter"=>"consultercompetences"
                          ,"id"=>"idcompetences"
                        )
    )
      ,"activity"=>"listercompetences"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"competences"
          )

  ),
  "consultercompetences"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"consulter"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editcompetences"
                          ,"lister"=>"listercompetences"
                          ,"id"=>"idcompetences"
                        )
    )
      ,"activity"=>"consultercompetences"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"competences"
          )

  ),
  "gestioncompetences"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"gestion"
      ,"view"=>array(
              "view"=>true
              ,"layout"=>"layout"
              ,"pages"=>array(
                "edit"=>"editcompetences"
                ,"lister"=>"listercompetences"
              )
          )
      ,"activity"=>"gestion"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competences"
      )

  ),
  "deletecompetences"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"delete"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"delete"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competences"
      )
  ),
  "savecompetences"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"save"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"save"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competences"
      )
  ),
  //activiter
  "editactiviter"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"edit"
      ,"view"=>array(
        "view"=>true
        ,"layout"=>false
        ,"pages"=>array(
              "edit"=>"editactiviter"
              ,"lister"=>"listeractiviter"
              //,"id"=>"idactiviter"
            )
      )
      ,"activity"=>"edit"
      ,"form"=>"formactiviter"
      ,"model"=>array(
          "table"=>"activiter"
      )
  ),

  "listeractiviter"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"lister"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editactiviter"
                          ,"lister"=>"listeractiviter"
                          ,"consulter"=>"consulteractiviter"
                          ,"id"=>"idactiviter"
                        )
    )
      ,"activity"=>"listeractiviter"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"activiter"
          )

  ),
  "consulteractiviter"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"consulter"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editactiviter"
                          ,"lister"=>"listeractiviter"
                          ,"id"=>"idactiviter"
                        )
    )
      ,"activity"=>"consulteractiviter"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"activiter"
          )

  ),
  "gestionactiviter"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"gestion"
      ,"view"=>array(
              "view"=>true
              ,"layout"=>"layout"
              ,"pages"=>array(
                "edit"=>"editactiviter"
                ,"lister"=>"listeractiviter"
              )
          )
      ,"activity"=>"gestion"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"activiter"
      )

  ),
  "deleteactiviter"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"delete"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"delete"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"activiter"
      )
  ),
  "saveactiviter"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"save"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"save"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"activiter"
      )
  ),
  //resources
  "editressources"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"edit"
      ,"view"=>array(
        "view"=>true
        ,"layout"=>false
        ,"pages"=>array(
              "edit"=>"editressources"
              ,"lister"=>"listerressources"
              //,"id"=>"idressources"
            )
      )
      ,"activity"=>"edit"
      ,"form"=>"formressources"
      ,"model"=>array(
          "table"=>"ressources"
      )
  ),

  "listerressources"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"lister"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editressources"
                          ,"lister"=>"listerressources"
                          ,"consulter"=>"consulterressources"
                          ,"id"=>"idressources"
                        )
    )
      ,"activity"=>"listerressources"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"ressources"
          )

  ),
  "consulterressources"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"consulter"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editressources"
                          ,"lister"=>"listerressources"
                          ,"id"=>"idressources"
                        )
    )
      ,"activity"=>"consulterressources"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"ressources"
          )

  ),
  "gestionressources"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"gestion"
      ,"view"=>array(
              "view"=>true
              ,"layout"=>"layout"
              ,"pages"=>array(
                "edit"=>"editressources"
                ,"lister"=>"listerressources"
              )
          )
      ,"activity"=>"gestion"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"ressources"
      )

  ),
  "deleteressources"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"delete"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"delete"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"ressources"
      )
  ),
  "saveressources"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"save"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"save"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"ressources"
      )
  ),
  ///action competencescontenue


  "editcompetencescontenue"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"edit"
      ,"view"=>array(
        "view"=>true
        ,"layout"=>false
        ,"pages"=>array(
              "edit"=>"editcompetencescontenue"
              ,"lister"=>"listercompetencescontenue"
              //,"id"=>"idcompetencescontenue"
            )
      )
      ,"activity"=>"edit"
      ,"form"=>"formcompetencescontenue"
      ,"model"=>array(
          "table"=>"competencescontenue"
      )
  ),

  "listercompetencescontenue"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"lister"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editcompetencescontenue"
                          ,"lister"=>"listercompetencescontenue"
                          ,"consulter"=>"consultercompetencescontenue"
                          ,"id"=>"idcompetencescontenue"
                        )
    )
      ,"activity"=>"listercompetencescontenue"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"competencescontenue"
          )

  ),
  "consultercompetencescontenue"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"consulter"
      ,"view"=>array(
                    "view"=>true
                    ,"layout"=>false
                    ,"pages"=>array(
                          "edit"=>"editcompetencescontenue"
                          ,"lister"=>"listercompetencescontenue"
                          ,"id"=>"idcompetencescontenue"
                        )
    )
      ,"activity"=>"consultercompetencescontenue"
      ,"form"=>false
      ,"model"=>array(
              "table"=>"competencescontenue"
          )

  ),
  "gestioncompetencescontenue"=>array(
      "Type"=>"simple"//"AJAX"
      ,'Role'=>"gestion"
      ,"view"=>array(
              "view"=>true
              ,"layout"=>"layout"
              ,"pages"=>array(
                "edit"=>"editcompetencescontenue"
                ,"lister"=>"listercompetencescontenue"
              )
          )
      ,"activity"=>"gestion"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competencescontenue"
      )

  ),
  "deletecompetencescontenue"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"delete"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"delete"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competencescontenue"
      )
  ),
  "savecompetencescontenue"=>array(
      "Type"=>"AJAX"//"AJAX"
      ,'Role'=>"save"
      ,"view"=>array("view"=>false,"layout"=>false)
      ,"activity"=>"save"
      ,"form"=>false
      ,"model"=>array(
          "table"=>"competencescontenue"
      )
  ),
