<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_centraleregional')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editcentraleregional","edit_editcentraleregional");
        loadPage("listercentraleregional","content_listercentraleregional");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_centraleregional")?></div>
            <div class="box-body" id="edit_editcentraleregional">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_centraleregional")?></div>
            <div class="box-body" id="content_listercentraleregional">

            </div>
        </div>
    </div>
</div>
