<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_sections')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editsections","edit_editsections");
        loadPage("listersections","content_listersections");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_sections")?></div>
            <div class="box-body" id="edit_editsections">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_sections")?></div>
            <div class="box-body" id="content_listersections">

            </div>
        </div>
    </div>
</div>
