<script type="text/javascript">


    function edit(params){

          $.ajax({
              type:"POST"
              ,url: "index.php?activity=editecole"
              ,data:{idecole:params,mode:"<?=$this->mode?>"}
              ,beforeSend:function(){
                  $('#edit_editecole').html("<i class='icon fa fa-gears'></i> chargement Encours...");
              }
              ,success:function(reponse){
                     $('#edit_editecole').html(reponse);
              }
          });

    }
    function consulter(params){

          $.ajax({
              type:"POST"
              ,url: "index.php?activity=consulterecole"
              ,data:{idecole:params}
              ,beforeSend:function(){
                  $('#edit_editecole').html("<i class='icon fa fa-gears'></i> chargement Encours...");
              }
              ,success:function(reponse){
                   $('#edit_editecole').html(reponse);
              }
          });

    }
    function deleteAct(params) {

        $.confirm({
            title: '<?=\lib\Langue::getString('Confirm_delete_ecole')?>!!',
            content: '<?=\lib\Langue::getString('Confirm_delete_ecole')?>!!',
            buttons: {
                confirm:{
                    text: "<i class='icon fa fa-trash'></i>Supprimer",
                    btnClass: 'btn-danger',

                    action :function () {
                        $.ajax({
                            type:"POST"
                            ,url: "index.php?activity=deleteecole"
                            ,data:{idecole:params}
                            ,beforeSend:function(){
                                $('#content_defin').html("<i class='icon fa fa-gears'></i> chargement Encours...");
                            }
                            ,success:function(reponse){
                                var obj = JSON.parse(reponse);
                                if(obj.status=="success") {
                                  loadPage("listerecole","content_listerecole");

                                }else{
                                    $.alert("<?=\lib\Langue::getString('Problem_delete_ecole')?>! "+obj.message);
                                }


                            }
                        });
                    }
                } ,
                cancel:  {
                    text: 'Annuler',
                    btnClass: 'btn-warning',
                    action: function(){
                        $.alert('<?=\lib\Langue::getString('Annuler_delete_ecole')?>');
                    }
                }
            }
        });
    }


</script>

<table class="table table-bordered table-striped">
    <caption><?=\lib\Langue::getString("Lister_ecole")?></caption>
    <thead>
    <tr>
        <?php foreach ($this->Header as $keyhead => $head):?>
            <th><?=\lib\Langue::getString($head)?></th>
        <?php endforeach;?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->liste as $e):?>
        <tr>
            <?php foreach ($this->Header as $keyhead => $head):?>
              <?php if(count($this->LinkedId) && isset($this->LinkedId['$keyhead'])):?>
              <td></td>
              <?php else :?>
                <td><?=$e["$keyhead"]?></td>
              <?php endif;?>
            <?php endforeach;?>
            <td>
                <button type="button" class="btn btn-danger" onclick="deleteAct('<?=$e['idecole']?>')"><i class="fa fa-trash"></i></button>

<button type="button" class="btn btn-success" onclick="edit('<?=$e['idecole']?>')"><i class="fa fa-edit"></i></button>

<button type="button" class="btn btn-info" onclick="consulter('<?=$e['idecole']?>')"><i class="fa fa-eye"></i></button>

            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
