<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_anneescoolaire')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editanneescoolaire","edit_editanneescoolaire");
        loadPage("listeranneescoolaire","content_listeranneescoolaire");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_anneescoolaire")?></div>
            <div class="box-body" id="edit_editanneescoolaire">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_anneescoolaire")?></div>
            <div class="box-body" id="content_listeranneescoolaire">

            </div>
        </div>
    </div>
</div>
