<script>

    $(function(){


        var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { },
            success: function() { },
            complete: function(response)
            {


                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                    $("#messageEditcompetences_Titre").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\lib\Langue::getString('Success_save_competences')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");

                       loadPage("listercompetences","content_listercompetences");

                    $("#competences")[0].reset();

                }else{

                    $("#messageEditcompetences_Titre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\lib\Langue::getString('Error_save_competences')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");


                }
                return true;

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#messageEditcompetences_Titre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'><?=\lib\Langue::getString('Success_save_competences')?></h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#competences").ajaxForm(optmyform);


    });
</script>

<div id="messageEditcompetences_Titre"></div>
<h1><?=\lib\Langue::getString("Edit_competences")?></h1>
<?=$this->form?>
