<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_contenucours')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editcontenucours","edit_editcontenucours");
        loadPage("listercontenucours","content_listercontenucours");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_contenucours")?></div>
            <div class="box-body" id="edit_editcontenucours">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_contenucours")?></div>
            <div class="box-body" id="content_listercontenucours">

            </div>
        </div>
    </div>
</div>
