<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\lib\Langue::getString('Chargement_competencescontenue')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editcompetencescontenue","edit_editcompetencescontenue");
        loadPage("listercompetencescontenue","content_listercompetencescontenue");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Edit_competencescontenue")?></div>
            <div class="box-body" id="edit_editcompetencescontenue">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\lib\Langue::getString("Lister_competencescontenue")?></div>
            <div class="box-body" id="content_listercompetencescontenue">

            </div>
        </div>
    </div>
</div>
